### ISSUE TITLE
feat: changelog-header configuration

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog-config-spec#15]
For standard-version, I would like to provide users with a `changelog-header` configuration option, which lets them customize the header in the CHANGELOG they're generating.

**Comment by jbottigliero** [comment]
Proposed as:

```js
        "header": {
            "type": "string",
            "description": "A string to be used as the main header section of the CHANGELOG.",
            "default": "# Changelog\n\n"
        },
```

---

I didn't go 1:1 with the [fallback in `standard-version`](https://github.com/conventional-changelog/standard-version/blob/master/lib/lifecycles/changelog.js#L29) for the `default` here... I would be open to switching it, I think it just comes down to whether or not the `defaults` found in the spec are expected to be the defaults for the `conventionalcommits` preset.

**Comment by jbottigliero** [comment]
I've gone ahead and added `header` in version `2.0.0` of the spec.
