### ISSUE TITLE
don't show test by default

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog-config-spec#16]
I noticed we currently show Tests by default:

```
{"type": "test", "section": "Tests"}
```

I don't think test refactoring is particularly useful to library consumers, so I'd argue we should hide this section.

**Comment by bcoe** [comment]
I'd probably make the same argument for `build`.

**Comment by jbottigliero** [comment]
@bcoe – I tend to agree here, and will make these changes... now that `standard-version` is using the spec, do you have any thoughts on how the versioning of this repository/package can best continue to support the implementation (#12)?

**Comment by bcoe** [comment]
@jbottigliero my gut would be just follow semver, a change like this probably would be a `major` as it changes the API surface -- not a huge deal since we're probably most of the folks using it, and it turns out version numbers are *free*!

If you make this change, want to submit the patch to `standard-version` after? excited to have you try out the new functionality :)

**Comment by jbottigliero** [comment]
Proposed as:

```js

"types": [
    {"type": "feat", "section": "Features"},
    {"type": "fix", "section": "Bug Fixes"},
    {"type": "chore", "hidden": true},
    {"type": "docs", "hidden": true},
    {"type": "style", "hidden": true},
    {"type": "refactor", "hidden": true},
    {"type": "perf", "hidden": true},
    {"type": "test", "hidden": true}
]
```

---

I _might_ have gone a little overboard here, but I basically just changed the `types.default` to cover all of the types mentioned in the published spec on conventionalcommits.org.

> 4. Others: commit types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the the Angular convention) recommends chore:, docs:, style:, refactor:, perf:, test:, and others.

**Comment by bcoe** [comment]
@jbottigliero this looks reasonable to me.
